services:
  metabase:
    image: metabase/metabase
    container_name: employee_performance_metabase
    ports:
      - "4000:3000"  # Exposes Metabase on port 3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: ayoub
      MB_DB_PASS: ayoub1319
      MB_DB_HOST: postgres
      MB_DB_SCHEMA: metabase_metadata
    networks:
      - employee_performance_network

networks:
  employee_performance_network:
    external: true  # Connects to the existing network created by your other Docker Compose files
